version: "3.8"

services:
  
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: vidly_web:1 # a version is for convenience once an image is deployed
    ports: 
      - 80:80
    restart: unless-stopped  
  
  api:
    build: ./backend
    image: vidly_api:1 # a version is for convenience once an image is deployed
    ports:
      - 3001:3001
    environment:
        DB_URL: mongodb://mongo/vidly # MIND mongo is a host name
    command: ./docker-entrypoint.sh
    restart: unless-stopped
    
  mongo:
    image: mongo:4.0.25-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped
    
volumes:
  vidly:
    
# Execute the command to build production build 
# docker-compose -f docker-compose.prod.yml build